// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMQEWlPtOx-SY4eQFSWTX1K6JXnVnKmk',
    appId: '1:856794807639:web:278217b5916adaf4129212',
    messagingSenderId: '856794807639',
    projectId: 'saluswell-app',
    authDomain: 'saluswell-app.firebaseapp.com',
    storageBucket: 'saluswell-app.appspot.com',
    measurementId: 'G-0QBJRVEFQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3DJRuweEaxQS4Xttxk_dyJByujaH00Q',
    appId: '1:856794807639:android:a9a3242cbde3c5d7129212',
    messagingSenderId: '856794807639',
    projectId: 'saluswell-app',
    storageBucket: 'saluswell-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ThP9i-D4jg4gbyaGfjOMF9_w4LgQ10k',
    appId: '1:856794807639:ios:f533919a0017f4ac129212',
    messagingSenderId: '856794807639',
    projectId: 'saluswell-app',
    storageBucket: 'saluswell-app.appspot.com',
    iosClientId: '856794807639-9t881qm5ovvtmt10o2rfocnl30e30477.apps.googleusercontent.com',
    iosBundleId: 'com.example.saluwellAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ThP9i-D4jg4gbyaGfjOMF9_w4LgQ10k',
    appId: '1:856794807639:ios:f533919a0017f4ac129212',
    messagingSenderId: '856794807639',
    projectId: 'saluswell-app',
    storageBucket: 'saluswell-app.appspot.com',
    iosClientId: '856794807639-9t881qm5ovvtmt10o2rfocnl30e30477.apps.googleusercontent.com',
    iosBundleId: 'com.example.saluwellAdminPanel',
  );
}
